-- MENU_CONFIG alineado con NAV_ITEMS (constants.ts)
-- Perfiles: 1 = Operador de Crédito, 2 = Jefe de Crédito, 3 = Administrador
-- Operador: sin Administración ni Configuración
-- Jefe: con Administración, sin Configuración
-- Administrador: acceso completo
--
-- Ejecutar en orden. Ajuste IDs de perfil si difieren en su BD.

DELETE FROM MENU_CONFIG WHERE ID_PERFIL IN (1, 2, 3);

-- =============================================================================
-- PERFIL 1 - OPERADOR DE CRÉDITO
-- =============================================================================

-- Pestañas principales (MENU_PATH NULL)
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Operación', NULL, 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Emisión', NULL, 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Cancelación', NULL, 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Consultas', NULL, 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Catálogos', NULL, 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reportes', NULL, 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Monitor', NULL, 1, 7, 'admin');

-- Operación
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Operación', 'operacion', 1, 1, 'admin');

-- Emisión
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Facturar', 'facturacion-articulos', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Notas de crédito', 'notas-credito', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Complemento de pagos', 'facturacion-complemento-pagos', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Retención de pagos', 'facturacion-retencion-pagos', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Carta Porte', 'facturacion-carta-porte', 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Nóminas', 'facturacion-nominas', 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Factura Global', 'facturacion-global', 1, 7, 'admin');

-- Cancelación
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Cancelación Masiva', 'facturacion-cancelacion', 1, 1, 'admin');

-- Consultas
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Tickets', 'consultas-tickets', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Facturas', 'consultas-facturas', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Refactura', 'refactura', 1, 3, 'admin');

-- Catálogos
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Productos o Servicios', 'catalogos-productos-servicios', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Clientes', 'catalogos-clientes', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Registro de Constancias', 'registro-cfdi', 1, 3, 'admin');

-- Reportes
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Boletas No Auditadas', 'reportes-boletas-no-auditadas', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reporte Ingreso-Facturación', 'reportes-ingreso-facturacion', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Integración Factura Global', 'reportes-integracion-factura-global', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Integración Clientes', 'reportes-integracion-clientes', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Facturación clientes posterior a Global', 'reportes-facturacion-clientes-global', 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Integración Sustitución CFDI', 'reportes-integracion-sustitucion-cfdi', 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Control de emisión de REP', 'reportes-control-emision-rep', 1, 7, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reportes REPgcp', 'reportes-repgcp', 1, 8, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Control de cambios', 'reportes-control-cambios', 1, 9, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Conciliación', 'reportes-conciliacion', 1, 10, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'REPs Sustituidos (Fiscal)', 'reportes-fiscales-reps-sustituidos', 1, 11, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reporte de Consulta Monederos', 'reportes-consulta-monederos', 1, 12, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reporte de Ventas Máquina Corporativas Serely Polu', 'reportes-ventas-maquina-corporativas', 1, 13, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Régimen de Facturación No Misma Boleta', 'reportes-regimen-facturacion-no-misma-boleta', 1, 14, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Doble Facturación Pendiente por Defencia', 'reportes-doble-facturacion-pendiente', 1, 15, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Sustitución en Proceso', 'reportes-sustitucion-en-proceso', 1, 16, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Cancelación Sustitución de Facturación', 'reportes-cancelacion-sustitucion-facturacion', 1, 17, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Saldo a Favor de Clientes', 'reportes-saldo-favor-clientes', 1, 18, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Orden de Módulos y Facturación', 'reportes-orden-modulos-facturacion', 1, 19, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Consulta de Usuarios', 'reportes-consulta-usuarios', 1, 20, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Consulta Tiendas de Total de Facturas Diarias', 'reportes-consulta-tiendas-facturas-diarias', 1, 21, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Validación por Importe Intereses', 'reportes-validacion-importe-intereses', 1, 22, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Conciliación Cambio de Sistema de Facturación', 'reportes-conciliacion-cambio-sistema', 1, 23, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Control de Complementos de Pago (REP) Generados por Ventas Corporativas', 'reportes-control-complementos-pago-rep', 1, 24, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reporte por Factura de Mercancía de Monederos', 'reportes-factura-mercancia-monederos', 1, 25, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Ventas Corporativas vs SAT', 'reportes-ventas-corporativas-vs-sat', 1, 26, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Captura Libre Complemento de Pago (REP)', 'reportes-captura-libre-complemento-pago', 1, 27, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Conciliación Sistema de Facturación de Boletas vs SAT', 'reportes-conciliacion-boletas-vs-sat', 1, 28, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Reporte de Trazabilidad de Boletas Canceladas', 'reportes-trazabilidad-boletas-canceladas', 1, 29, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Estatus Actualizar SAT de CFDI por Petición', 'reportes-estatus-actualizar-sat-cfdi', 1, 30, 'admin');

-- Monitor
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Bitácora', 'monitor-bitacora', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Disponibilidad', 'monitor-disponibilidad', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Logs', 'monitor-logs', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Decodificador', 'monitor-decodificador', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 1, 'Permisos', 'monitor-permisos', 1, 5, 'admin');

-- =============================================================================
-- PERFIL 2 - JEFE DE CRÉDITO (Operador + Administración)
-- =============================================================================

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Operación', NULL, 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Emisión', NULL, 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Cancelación', NULL, 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Consultas', NULL, 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Catálogos', NULL, 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Administración', NULL, 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reportes', NULL, 1, 7, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Monitor', NULL, 1, 8, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Operación', 'operacion', 1, 1, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Facturar', 'facturacion-articulos', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Notas de crédito', 'notas-credito', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Complemento de pagos', 'facturacion-complemento-pagos', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Retención de pagos', 'facturacion-retencion-pagos', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Carta Porte', 'facturacion-carta-porte', 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Nóminas', 'facturacion-nominas', 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Factura Global', 'facturacion-global', 1, 7, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Cancelación Masiva', 'facturacion-cancelacion', 1, 1, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Tickets', 'consultas-tickets', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Facturas', 'consultas-facturas', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Refactura', 'refactura', 1, 3, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Productos o Servicios', 'catalogos-productos-servicios', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Clientes', 'catalogos-clientes', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Registro de Constancias', 'registro-cfdi', 1, 3, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Empleados', 'admin-empleados', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Operación (admin)', 'operacion-admin', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Administrar facturas – acciones', 'admin-facturas-acciones', 1, 3, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Boletas No Auditadas', 'reportes-boletas-no-auditadas', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reporte Ingreso-Facturación', 'reportes-ingreso-facturacion', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Integración Factura Global', 'reportes-integracion-factura-global', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Integración Clientes', 'reportes-integracion-clientes', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Facturación clientes posterior a Global', 'reportes-facturacion-clientes-global', 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Integración Sustitución CFDI', 'reportes-integracion-sustitucion-cfdi', 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Control de emisión de REP', 'reportes-control-emision-rep', 1, 7, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reportes REPgcp', 'reportes-repgcp', 1, 8, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Control de cambios', 'reportes-control-cambios', 1, 9, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Conciliación', 'reportes-conciliacion', 1, 10, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'REPs Sustituidos (Fiscal)', 'reportes-fiscales-reps-sustituidos', 1, 11, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reporte de Consulta Monederos', 'reportes-consulta-monederos', 1, 12, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reporte de Ventas Máquina Corporativas Serely Polu', 'reportes-ventas-maquina-corporativas', 1, 13, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Régimen de Facturación No Misma Boleta', 'reportes-regimen-facturacion-no-misma-boleta', 1, 14, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Doble Facturación Pendiente por Defencia', 'reportes-doble-facturacion-pendiente', 1, 15, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Sustitución en Proceso', 'reportes-sustitucion-en-proceso', 1, 16, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Cancelación Sustitución de Facturación', 'reportes-cancelacion-sustitucion-facturacion', 1, 17, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Saldo a Favor de Clientes', 'reportes-saldo-favor-clientes', 1, 18, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Orden de Módulos y Facturación', 'reportes-orden-modulos-facturacion', 1, 19, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Consulta de Usuarios', 'reportes-consulta-usuarios', 1, 20, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Consulta Tiendas de Total de Facturas Diarias', 'reportes-consulta-tiendas-facturas-diarias', 1, 21, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Validación por Importe Intereses', 'reportes-validacion-importe-intereses', 1, 22, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Conciliación Cambio de Sistema de Facturación', 'reportes-conciliacion-cambio-sistema', 1, 23, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Control de Complementos de Pago (REP) Generados por Ventas Corporativas', 'reportes-control-complementos-pago-rep', 1, 24, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reporte por Factura de Mercancía de Monederos', 'reportes-factura-mercancia-monederos', 1, 25, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Ventas Corporativas vs SAT', 'reportes-ventas-corporativas-vs-sat', 1, 26, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Captura Libre Complemento de Pago (REP)', 'reportes-captura-libre-complemento-pago', 1, 27, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Conciliación Sistema de Facturación de Boletas vs SAT', 'reportes-conciliacion-boletas-vs-sat', 1, 28, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Reporte de Trazabilidad de Boletas Canceladas', 'reportes-trazabilidad-boletas-canceladas', 1, 29, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Estatus Actualizar SAT de CFDI por Petición', 'reportes-estatus-actualizar-sat-cfdi', 1, 30, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Bitácora', 'monitor-bitacora', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Disponibilidad', 'monitor-disponibilidad', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Logs', 'monitor-logs', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Decodificador', 'monitor-decodificador', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 2, 'Permisos', 'monitor-permisos', 1, 5, 'admin');

-- =============================================================================
-- PERFIL 3 - ADMINISTRADOR (acceso completo)
-- =============================================================================

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Operación', NULL, 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Emisión', NULL, 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Cancelación', NULL, 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Consultas', NULL, 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Catálogos', NULL, 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Administración', NULL, 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reportes', NULL, 1, 7, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Monitor', NULL, 1, 8, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Configuración', NULL, 1, 9, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Operación', 'operacion', 1, 1, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Facturar', 'facturacion-articulos', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Notas de crédito', 'notas-credito', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Complemento de pagos', 'facturacion-complemento-pagos', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Retención de pagos', 'facturacion-retencion-pagos', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Carta Porte', 'facturacion-carta-porte', 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Nóminas', 'facturacion-nominas', 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Factura Global', 'facturacion-global', 1, 7, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Cancelación Masiva', 'facturacion-cancelacion', 1, 1, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Tickets', 'consultas-tickets', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Facturas', 'consultas-facturas', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Refactura', 'refactura', 1, 3, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Productos o Servicios', 'catalogos-productos-servicios', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Clientes', 'catalogos-clientes', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Registro de Constancias', 'registro-cfdi', 1, 3, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Empleados', 'admin-empleados', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Operación (admin)', 'operacion-admin', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Administrar facturas – acciones', 'admin-facturas-acciones', 1, 3, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Boletas No Auditadas', 'reportes-boletas-no-auditadas', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reporte Ingreso-Facturación', 'reportes-ingreso-facturacion', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Integración Factura Global', 'reportes-integracion-factura-global', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Integración Clientes', 'reportes-integracion-clientes', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Facturación clientes posterior a Global', 'reportes-facturacion-clientes-global', 1, 5, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Integración Sustitución CFDI', 'reportes-integracion-sustitucion-cfdi', 1, 6, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Control de emisión de REP', 'reportes-control-emision-rep', 1, 7, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reportes REPgcp', 'reportes-repgcp', 1, 8, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Control de cambios', 'reportes-control-cambios', 1, 9, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Conciliación', 'reportes-conciliacion', 1, 10, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'REPs Sustituidos (Fiscal)', 'reportes-fiscales-reps-sustituidos', 1, 11, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reporte de Consulta Monederos', 'reportes-consulta-monederos', 1, 12, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reporte de Ventas Máquina Corporativas Serely Polu', 'reportes-ventas-maquina-corporativas', 1, 13, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Régimen de Facturación No Misma Boleta', 'reportes-regimen-facturacion-no-misma-boleta', 1, 14, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Doble Facturación Pendiente por Defencia', 'reportes-doble-facturacion-pendiente', 1, 15, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Sustitución en Proceso', 'reportes-sustitucion-en-proceso', 1, 16, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Cancelación Sustitución de Facturación', 'reportes-cancelacion-sustitucion-facturacion', 1, 17, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Saldo a Favor de Clientes', 'reportes-saldo-favor-clientes', 1, 18, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Orden de Módulos y Facturación', 'reportes-orden-modulos-facturacion', 1, 19, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Consulta de Usuarios', 'reportes-consulta-usuarios', 1, 20, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Consulta Tiendas de Total de Facturas Diarias', 'reportes-consulta-tiendas-facturas-diarias', 1, 21, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Validación por Importe Intereses', 'reportes-validacion-importe-intereses', 1, 22, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Conciliación Cambio de Sistema de Facturación', 'reportes-conciliacion-cambio-sistema', 1, 23, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Control de Complementos de Pago (REP) Generados por Ventas Corporativas', 'reportes-control-complementos-pago-rep', 1, 24, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reporte por Factura de Mercancía de Monederos', 'reportes-factura-mercancia-monederos', 1, 25, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Ventas Corporativas vs SAT', 'reportes-ventas-corporativas-vs-sat', 1, 26, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Captura Libre Complemento de Pago (REP)', 'reportes-captura-libre-complemento-pago', 1, 27, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Conciliación Sistema de Facturación de Boletas vs SAT', 'reportes-conciliacion-boletas-vs-sat', 1, 28, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Reporte de Trazabilidad de Boletas Canceladas', 'reportes-trazabilidad-boletas-canceladas', 1, 29, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Estatus Actualizar SAT de CFDI por Petición', 'reportes-estatus-actualizar-sat-cfdi', 1, 30, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Bitácora', 'monitor-bitacora', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Disponibilidad', 'monitor-disponibilidad', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Logs', 'monitor-logs', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Decodificador', 'monitor-decodificador', 1, 4, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Permisos', 'monitor-permisos', 1, 5, 'admin');

INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Temas', 'configuracion-temas', 1, 1, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Empresa', 'configuracion-empresa', 1, 2, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Mensajes de Correo', 'configuracion-correo', 1, 3, 'admin');
INSERT INTO MENU_CONFIG (ID_CONFIG, ID_PERFIL, MENU_LABEL, MENU_PATH, IS_VISIBLE, ORDEN, USUARIO_CREACION) VALUES (MENU_CONFIG_SEQ.NEXTVAL, 3, 'Configuración de Menús', 'configuracion-menus', 1, 4, 'admin');

COMMIT;
